class Words:
    def __init__(self):
        pass

    def genWords(self) -> list:
        wordsLis = [
            "aback", "abase", "abate", "abbey", "abbot", "abide", "abled", "abode", "abort", "about",
            "above", "abuse", "abyss", "ached", "aches", "acids", "acorn", "acres", "acted", "actor",
            "acute", "adage", "adapt", "added", "adder", "adept", "adieu", "admin", "admit", "adobe",
            "adopt", "adore", "adorn", "adult", "affix", "afire", "afoot", "after", "again", "agent",
            "agile", "aging", "aglow", "agree", "ahead", "aided", "aimed", "aired", "aisle", "alarm",
            "album", "alert", "algae", "alias", "alibi", "alien", "align", "alike", "alive", "alley",
            "allow", "alloy", "aloft", "alone", "along", "aloof", "aloud", "alpha", "altar", "alter",
            "amaze", "amber", "amend", "amino", "amiss", "amity", "among", "angel", "anger", "angle",
            "angry", "apart", "apple", "apply", "apron", "arena", "argue", "arise", "armor", "aroma",
            "array", "arrow", "arson", "ashes", "aside", "asked", "asset", "atlas", "attic", "audio",
            "audit", "augur", "aunty", "avail", "award", "aware", "awful", "bacon", "badge", "badly",
            "bagel", "baker", "balmy", "banjo", "barge", "basil", "batch", "beach", "beads", "beard",
            "beast", "begin", "being", "belly", "bench", "berry", "birth", "bison", "blade", "blame",
            "blank", "blaze", "bleak", "blend", "bless", "blind", "blink", "block", "blond", "blood",
            "bloom", "blown", "blues", "bluff", "board", "boast", "bonus", "boost", "booth", "boots",
            "bored", "borne", "bound", "bowel", "brain", "brake", "brand", "brave", "bread", "break",
            "breed", "bride", "brief", "brine", "bring", "broad", "broke", "brown", "brush", "buddy",
            "build", "built", "bulky", "bunch", "burnt", "burst", "cabin", "cable", "cacao", "cache",
            "caged", "candy", "canal", "canny", "canoe", "canon", "carry", "carve", "cause", "cease",
            "cedar", "chain", "chair", "chalk", "charm", "chart", "chase", "cheap", "check", "cheek",
            "cheer", "chess", "chest", "chief", "child", "chili", "chill", "china", "choir", "choke",
            "chord", "chose", "chunk", "cider", "cigar", "claim", "clash", "clerk", "click", "cliff",
            "climb", "cling", "clock", "clone", "close", "cloth", "cloud", "clown", "coach", "coast",
            "cobra", "colon", "color", "comet", "comic", "comma", "conch", "coral", "couch", "count",
            "court", "cover", "crack", "craft", "crane", "crash", "crawl", "crazy", "cream", "creek",
            "crest", "cried", "cries", "crime", "crisp", "cross", "crowd", "crown", "crude", "cruel",
            "crumb", "crush", "cubic", "cumin", "curve", "cycle", "daily", "dairy", "daisy", "dance",
            "dated", "dealt", "death", "debit", "debug", "decay", "decor", "defer", "delay", "delta",
            "dense", "depth", "devil", "diary", "diner", "dingy", "disco", "ditch", "diver", "dizzy",
            "dodge", "doing", "donor", "doubt", "dozen", "draft", "drain", "drama", "drawn", "dream",
            "dress", "drift", "drink", "drive", "droid", "drove", "drown", "drums", "dryer", "eager",
            "eagle", "early", "earth", "eased", "edges", "edged", "eight", "elder", "elect", "elite",
            "empty", "enact", "ended", "enemy", "enjoy", "enter", "entry", "equal", "error", "essay",
            "event", "every", "evoke", "exact", "exalt", "excel", "exile", "exist", "extra", "fable",
            "faced", "faces", "faint", "fairy", "faith", "false", "fancy", "farce", "fatal", "favor",
            "feast", "fence", "ferry", "fever", "fiber", "field", "fiery", "fifth", "fifty", "fight",
            "final", "finer", "first", "flair", "flame", "flank", "flash", "fleet", "flesh", "flint",
            "float", "flock", "flood", "floor", "flour", "flown", "fluid", "flute", "focus", "force",
            "forge", "forth", "forty", "found", "frame", "fraud", "fresh", "fried", "front", "frost",
            "fruit", "funny", "giant", "given", "glass", "glide", "glory", "glove", "gnome", "goals",
            "grace", "grade", "grain", "grand", "grant", "grape", "graph", "grass", "grave", "great",
            "greed", "green", "greet", "grind", "gross", "group", "grove", "grown", "guard", "guest",
            "guide", "guilt", "habit", "happy", "harsh", "haste", "haunt", "heart", "heavy", "hedge",
            "height", "hello", "hence", "herbs", "hobby", "honor", "horse", "hotel", "house", "human",
            "humor", "hurry", "ideal", "image", "imply", "index", "input", "irony", "issue", "ivory",
            "jelly", "jewel", "joint", "judge", "juice", "jumbo", "jumps", "karma", "kneel", "knife",
            "known", "label", "labor", "laden", "laser", "later", "laugh", "layer", "learn", "lease",
            "lemon", "level", "light", "limit", "linen", "lined", "liver", "local", "logic", "loner",
            "loose", "lover", "lucky", "lunar", "lunch", "magic", "major", "maker", "march", "marry",
            "match", "maybe", "mayor", "meant", "meaty", "medal", "metal", "meter", "might", "miner",
            "minor", "mixed", "model", "money", "month", "moral", "motel", "motor", "mount", "mouse",
            "mouth", "movie", "music", "naive", "nasty", "naval", "needy", "nerve", "never", "newer",
            "night", "noble", "noise", "north", "novel", "nurse", "oasis", "ocean", "offer", "often",
            "olive", "onion", "opera", "orbit", "order", "organ", "other", "ounce", "outer", "owner",
            "oxide", "paint", "panel", "panic", "paper", "party", "patch", "pause", "peace", "pearl",
            "pedal", "penny", "perch", "phase", "phone", "photo", "piano", "piece", "pilot", "pitch",
            "place", "plain", "plane", "plant", "plate", "plead", "plumb", "point", "poise", "polar",
            "porch", "pound", "power", "press", "price", "pride", "prime", "print", "prize", "proof",
            "proud", "prove", "queen", "quick", "quiet", "quirk", "quota", "quote", "radar", "radio",
            "raise", "ranch", "range", "rapid", "rated", "ratio", "reach", "react", "ready", "realm",
            "rebel", "refer", "relax", "renew", "reply", "reset", "rider", "ridge", "right", "risky",
            "rival", "river", "roast", "robot", "rocky", "rogue", "roman", "rough", "round", "route",
            "royal", "rugby", "ruler", "rural", "saint", "salad", "sandy", "sauce", "scale", "scare",
            "scene", "scent", "scold", "scoop", "scope", "score", "scout", "scrap", "screw", "seams",
            "seeds", "seize", "sense", "serve", "setup", "shack", "shade", "shaft", "shake", "shall",
            "shame", "shape", "share", "shark", "sharp", "sheep", "sheet", "shelf", "shell", "shift",
            "shine", "shirt", "shock", "shoot", "shore", "short", "shout", "shown", "sides", "siege",
            "sight", "signs", "silly", "since", "siren", "skill", "skirt", "skull", "slave", "sleep",
            "slice", "slope", "small", "smart", "smell", "smile", "smoke", "snack", "snake", "sneak",
            "solar", "solid", "solve", "sound", "south", "space", "spare", "spark", "speak", "speed",
            "spell", "spend", "spice", "spine", "spite", "split", "spoke", "sport", "spout", "spray",
            "stack", "staff", "stage", "stain", "stake", "stand", "stare", "start", "state", "steam",
            "steel", "steep", "stick", "still", "stock", "stone", "stool", "storm", "story", "strap",
            "straw", "strip", "stuck", "study", "stuff", "style", "sugar", "sunny", "super", "sweet",
            "sword", "table", "taken", "tasty", "teach", "tease", "teeth", "tempo", "thank", "theft",
            "their", "theme", "there", "these", "thick", "thief", "thing", "think", "third", "those",
            "three", "threw", "throw", "thumb", "tiger", "tight", "timer", "tired", "title", "today",
            "token", "tooth", "topic", "total", "touch", "tough", "tower", "trace", "track", "trade",
            "trail", "train", "treat", "trend", "trial", "tribe", "trick", "tried", "truck", "truly",
            "trump", "trust", "truth", "tulip", "tuned", "twice", "under", "unite", "unity", "until",
            "upper", "upset", "urban", "usage", "usual", "vague", "valid", "value", "vapor", "vault",
            "venue", "verse", "video", "vigor", "villa", "vinyl", "viola", "virus", "vital", "vivid",
            "vocal", "voice", "voter", "wacky", "wafer", "wager", "wages", "wagon", "waist", "waltz",
            "waste", "watch", "water", "weary", "weigh", "whale", "wheat", "wheel", "where", "which",
            "while", "whine", "whirl", "white", "whole", "whose", "widen", "width", "wills", "winds",
            "wings", "wiped", "wiser", "woman", "women", "world", "worry", "wound", "woven", "wrath",
            "wreck", "wrist", "write", "wrong", "wrote", "xenon", "yacht", "yearn", "yeast", "yield",
            "young", "youth", "zebra", "zesty", "zones"
        ]

        return wordsLis